fragment PageParts on Page {
  pageBlocks3 {
    __typename
    ... on PagePageBlocks3NestedBlocka {
      nestedBlock1 {
        __typename
        ... on PagePageBlocks3NestedBlockaNestedBlock1Items {
          nestedBlockc {
            __typename
            title
          }
        }
      }
      nestedBlock2 {
        __typename
        ... on PagePageBlocks3NestedBlockaNestedBlock2Items {
          nestedBlockc {
            __typename
            title
          }
        }
      }
    }
  }
}
