fragment PageParts on Page {
  pageBlocks3 {
    __typename
    ... on PagePageBlocks3NestedBlocka {
      nestedBlockb {
        __typename
        ... on PagePageBlocks3NestedBlockaNestedBlockbItems {
          nestedBlockc {
            __typename
            title
          }
        }
      }
    }
  }
}
